name: Swift Xcode Tests
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Show Xcode Version
      run: xcodebuild -version
      
    - name: Build and Test
      run: |
        xcodebuild test -scheme calc -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}